### ISSUE TITLE
Error: Invalid openssl exit code: 126

### ISSUE THREAD

**Issue by pematt** [alexandredavi/openssl-lambda-layer#5]
I get the error below while running your published version arn:aws:lambda:eu-north-1:034541671702:layer:openssl-lambda:1:

% openssl pkcs12 -in /tmp/981d02135e81e632c70be736f9f050dd1712f27f -passin file:/tmp/b186b8d22fc87c7f711025fb2e51348517eafe2c -nodes
/opt/bin/openssl: /opt/bin/openssl: cannot execute binary file
, queryConfig: undefined Error: Invalid openssl exit code: 126

**Comment by pematt** [comment]
My apologies - I had the wrong architecture, closing.

**Comment by probablyrosie** [comment]
Hi! I am running into the same problem, would you clarify what you changed in your architecture?

**Comment by pematt** [comment]
> Hi! I am running into the same problem, would you clarify what you changed in your architecture?

I changed the 'architecture' to x86_64 in serverless.yml:
```
provider:
  name: aws
  runtimeManagement: onFunctionUpdate
  versionFunctions: false
  runtime: nodejs18.x
  architecture: x86_64
  ...
```
